# No dots! Look in the current working directory
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlite:jobs.db}
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate settings
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

